epochs: 200
batch: -1
imgsz: 640
device: 0
patience: 50

workers: 8
rect: true
device: 0

project: "ml_data/experiments"
name: "ray_tune_26s_real"
optimizer: "auto"
val: true                # val during training
save: true               # save checkpoints