epochs: 200
batch: -1
imgsz: 640
device: 0
patience: 50

workers: 0
rect: true

name: "fsoco_train"
optimizer: "auto"
val: true                # val during training
save: true               # save checkpoints
tensorboard: false       # disabled for mlflow only